### ISSUE TITLE
could u plz upload the codes of drawing Figure 1 and Figure 2 in your paper？

### ISSUE THREAD

**Issue by RoseMob** [P2333/SCORE#4]
i wanna know how to do it

**Comment by P2333** [comment]
Hi,

The toy demos in Figures 1 and 2 can be plotted following the guidelines in [https://github.com/P2333/SCORE#toy-demos](https://github.com/P2333/SCORE#toy-demos). Namely, you can first use the script `generate_toy_demo.py` to generate toy demo data and then plot the figures by MATLAB script `plot_toy_demo.m` (plotting with `Matplotlib` in python is an alternative choice).

**Comment by RoseMob** [comment]
thank u!!!

**Comment by RoseMob** [comment]
> The

thank u!
